.\main.exe --instance .\instances\tai12a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai12a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai12a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai12a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai12a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai12a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai12a.dat --alpha 100 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai25a.dat --alpha 100 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai35a.dat --alpha 100 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai50a.dat --alpha 100 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai60a.dat --alpha 100 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai80a.dat --alpha 100 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 0 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 3 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 5 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 10 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 15 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 20 --best_improvement 0
.\main.exe --instance .\instances\tai100a.dat --alpha 100 --best_improvement 0

.\main.exe --instance .\instances\tai12a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai12a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai12a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai12a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai12a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai12a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai12a.dat --alpha 100 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai25a.dat --alpha 100 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai35a.dat --alpha 100 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai50a.dat --alpha 100 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai60a.dat --alpha 100 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai80a.dat --alpha 100 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 0 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 3 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 5 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 10 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 15 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 20 --best_improvement 1
.\main.exe --instance .\instances\tai100a.dat --alpha 100 --best_improvement 1